---
apiVersion: v1
kind: Pod
metadata:
  labels: 
    app: jenkins-molecule-slave
spec:
  containers:
  - name: jnlp
    image: nexus.lab.wfhdesign.nl/jenkins-slave
    tty: true
  - name: ansible
    image: nexus.lab.wfhdesign.nl/ansible
    command:
    - cat
    tty: true
  imagePullSecrets:
  - name: nexus-auth

