---
apiVersion: v1
kind: Pod
metadata:
  labels: 
    app: jenkins-molecule-slave
spec:
  securityContext:
    runAsUser: 10000
    fsGroup: 10000
  containers:
    - name: jnlp
      image: nexus.lab.wfhdesign.nl/jenkins-slave
      tty: true
    - name: ansible
      image: nexus.lab.wfhdesign.nl/ansible
      command:
        - cat
    tty: true
  imagePullSecrets:
    - name: nexus-auth

